#!/bin/bash
################################################################
# Display on terminal All resulting files from sub-directories #
################################################################
for i in `ls `;

do

if test -d "$i"
  then

cd $i;
cat result.txt;
cd ..

fi
done
